<?php

namespace eventBundle\Repository;

/**
 * PlanEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanEventRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $str
     * @return array
     */
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT titre
                FROM eventBundle:evennements e eventBundle:PlanEvent p 
                WHERE e.id = :str AND p.id = :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
