<?php

namespace cantineBundle\Repository;

/**
 * platsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class platsRepository extends \Doctrine\ORM\EntityRepository
{
}
